# Explicit opt-in helper. No downloading or automatic native build occurs here.
function(penny_link_sodium target output_root)
  if(NOT ANDROID OR NOT ANDROID_NATIVE_API_LEVEL STREQUAL "26")
    message(FATAL_ERROR "Penny sodium requires Android API 26")
  endif()
  if(NOT ANDROID_NDK_REVISION STREQUAL "28.2.13676358")
    message(FATAL_ERROR "Penny sodium requires NDK 28.2.13676358")
  endif()
  file(REAL_PATH "${ANDROID_NDK}/build/cmake/android.toolchain.cmake" expected_toolchain)
  file(REAL_PATH "${CMAKE_TOOLCHAIN_FILE}" actual_toolchain)
  file(STRINGS "${ANDROID_NDK}/source.properties" ndk_revision REGEX "^Pkg.Revision = ")
  if(NOT expected_toolchain STREQUAL actual_toolchain OR NOT ndk_revision STREQUAL "Pkg.Revision = 28.2.13676358")
    message(FATAL_ERROR "Use the official pinned NDK toolchain and metadata")
  endif()
  if(TARGET penny_sodium)
    message(FATAL_ERROR "Refusing a pre-existing penny_sodium target; call this helper once")
  endif()
  if(NOT ANDROID_ABI MATCHES "^(arm64-v8a|armeabi-v7a|x86|x86_64)$")
    message(FATAL_ERROR "Unsupported Penny sodium ABI")
  endif()
  if(NOT IS_ABSOLUTE "${output_root}")
    message(FATAL_ERROR "Supply the absolute verified build output path")
  endif()
  file(READ "${output_root}/build-result.json" result)
  string(JSON built_ndk GET "${result}" ndk)
  string(JSON built_api GET "${result}" api)
  if(NOT built_ndk STREQUAL "28.2.13676358" OR NOT built_api EQUAL 26)
    message(FATAL_ERROR "Native build configuration mismatch")
  endif()
  set(manifest "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../source-manifest.json")
  file(SHA256 "${manifest}" manifest_hash)
  string(JSON recorded_manifest_hash GET "${result}" manifestSha256)
  if(NOT manifest_hash STREQUAL recorded_manifest_hash)
    message(FATAL_ERROR "Build output does not match the source manifest")
  endif()
  set(library "${output_root}/${ANDROID_ABI}/lib/libsodium.a")
  file(SHA256 "${library}" archive_hash)
  string(JSON count LENGTH "${result}" builds)
  math(EXPR last "${count} - 1")
  set(matches 0)
  foreach(index RANGE 0 ${last})
    string(JSON abi GET "${result}" builds ${index} abi)
    if(abi STREQUAL ANDROID_ABI)
      math(EXPR matches "${matches} + 1")
      string(JSON expected_hash GET "${result}" builds ${index} archiveSha256)
      if(NOT archive_hash STREQUAL expected_hash)
        message(FATAL_ERROR "Static archive digest mismatch")
      endif()
      string(JSON header_count LENGTH "${result}" builds ${index} headersSha256)
      file(GLOB_RECURSE actual_headers LIST_DIRECTORIES false RELATIVE "${output_root}/${ANDROID_ABI}/include" "${output_root}/${ANDROID_ABI}/include/*")
      list(LENGTH actual_headers actual_header_count)
      if(NOT header_count GREATER 0 OR NOT header_count EQUAL actual_header_count)
        message(FATAL_ERROR "Installed header inventory mismatch")
      endif()
      foreach(header IN LISTS actual_headers)
        set(header_path "${output_root}/${ANDROID_ABI}/include/${header}")
        if(IS_SYMLINK "${header_path}")
          message(FATAL_ERROR "Installed header links are forbidden")
        endif()
        string(JSON expected_header_hash GET "${result}" builds ${index} headersSha256 "${header}")
        file(SHA256 "${header_path}" header_hash)
        if(NOT header_hash STREQUAL expected_header_hash)
          message(FATAL_ERROR "Installed header digest mismatch")
        endif()
      endforeach()
    endif()
  endforeach()
  if(NOT matches EQUAL 1)
    message(FATAL_ERROR "Missing or duplicated ABI provenance")
  endif()
  if(NOT TARGET penny_sodium)
    add_library(penny_sodium STATIC IMPORTED)
    set_target_properties(penny_sodium PROPERTIES
      IMPORTED_LOCATION "${library}"
      INTERFACE_INCLUDE_DIRECTORIES "${output_root}/${ANDROID_ABI}/include")
  endif()
  target_link_libraries(${target} PRIVATE penny_sodium)
  target_link_options(${target} PRIVATE "-Wl,-z,defs" "-Wl,-z,max-page-size=16384" "-Wl,-z,common-page-size=16384")
endfunction()
